### ISSUE TITLE
Prevent xmlns="null"

### ISSUE THREAD

**Issue by ewsterrenburg** [aerhard/linter-autocomplete-jing#18]
Hello,

Hello @aerhard ,

When using the autocomplete functionality, for each element I create, the attribute **xmlns="null"** is added (excerpts of xml and xsd below). I don't know enough about these kind of things to suspect if this is an issue with the xml, underlying xsd or the auto-completer. I know enough that it is annoying and it would help if this would not happen (perhaps as an option).

(If something is clearly wrong with either the xml or xsd, I'm really sorry for bothering you with my stupidity :)

**xml:**
`﻿<?xml version="1.0" encoding="UTF-8"?>`
`<mnu version="5.2.0" xsi:noNamespaceSchemaLocation="..\..\..\xsd_520\mnu.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`
`...`
`</mnu>`

**xsd:**
`<?xml version="1.0" encoding="UTF-8"?>`
`<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">`
`...`
`</xs:schema>`

**Comment by aerhard** [comment]
Hi - this looks like a bug... thanks for reporting it!

**Comment by ewsterrenburg** [comment]
You're welcome.
I can provide full versions of xml and xsd if that helps you.

**Comment by aerhard** [comment]
yes, that would be great!

**Comment by ewsterrenburg** [comment]
Since adding files is failing, I have created a [gist](https://gist.github.com/ewsterrenburg/b7718d3a75e60ac0259f81656dad9a65)

**Comment by aerhard** [comment]
That's fine -- thanks!

**Comment by aerhard** [comment]
I've fixed it -- created a couple of new test files but also checked with your XML. Needed to add support for schema files without a target namespace. I'm currently adding comments and CDATA sections to the autocomplete suggestions; after that I'll update the Atom repo...

**Comment by ewsterrenburg** [comment]
That's quick... thanks!!!
