### ISSUE TITLE
Add support for XML catalogs

### ISSUE THREAD

**Issue by stefan-jung** [aerhard/linter-autocomplete-jing#2]
Please implement support for [XML catalogs](https://en.wikipedia.org/wiki/XML_Catalog).

**Comment by aerhard** [comment]
I'll take a closer look -- probably need to do some refactorings in the non-Jing parts in Java, but it shouldn't be hard to add...

**Comment by aerhard** [comment]
I've started implementing the catalog support -- it's still work in progress, see https://github.com/aerhard/linter-jing/tree/catalog Resolving schema references in xml-model processing  instructions already works but I'd like to add more tests -- and catalogs are not yet supported for DTDs and XSDs...

**Comment by aerhard** [comment]
Catalogs should work now -- I've updated the Atom package. Please leave a comment if anything is missing or not working as expected!

**Comment by infotexture** [comment]
How do I point linter-jing to a local catalog file?

**Comment by aerhard** [comment]
You can add the path in the linter-jing package settings -- open the settings view (navigate to Packages / Settings View / Open in the main menu or press Ctrl and ,). From there, select "Packages", enter "linter-jing" in the search box and then click the "Settings" button. You should then see the package-specific options with the XML Catalog text field (as an example, mine has `/home/ahlsen/dev/linter-jing/spec/catalog/catalog.xml` as content)
