### ISSUE TITLE
xsi:noNamespaceSchemaLocation cannot handle spaces in filepath

### ISSUE THREAD

**Issue by ewsterrenburg** [aerhard/linter-autocomplete-jing#37]
`<?xml version="1.0" encoding="utf-8"?>
   <geodbupdate version="1.00.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\NL01031\Box Sync\BC9815 Technical Data Exchange\900 Geonis Blaeu product\Versie 1.6 release\02 Software\Desktop\GEONIS Structuur\xsd\updatemodul.xsd">
...
  </updateset>
</geodbupdate>
`

results in a Jing Warning:

"Could not process schema or catalog: exception "java.io.FileNotFoundException" thrown: schema_reference.4: Failed to read schema document 'file:/C:/Users/NL01031/Box', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.: C:\Users\NL01031\Box (The system cannot find the file specified)at line 1 col 1"

Don't know if this is a linter-auto-complete issue or a jing issue.

**Comment by aerhard** [comment]
thanks for reporting! There's a bug in how the content of `xsi:noNamespaceSchemaLocation` is being processed -- I'll fix it and update the Atom package

**Comment by aerhard** [comment]
fixing that bug in JavaScript didn't solve the issue - I'll check if that's something that can be fixed on the Java side. According to the specs, spaces are allowed but discouraged in the datatype of `xsi:noNamespaceSchemaLocation`, `anyURI`. In any case, things should definitely work when you refer to the schema with a file URI (`file:///C:/Users/NL01031/Box%20Sync/...`) instead of a path

**Comment by ewsterrenburg** [comment]
Hi @aerhard,

I can confirm the uri is working with spaces, yet we do have xml's that refer to a relative path. Of course for editing, there's plenty of workarounds, so the issue is not that urgent. None-the-less it'd be nice if we could work with spaces in a filepath :)

Final words: thanks for this package! It makes working with xml a lot more pleasant...

**Comment by aerhard** [comment]
I'm glad it's useful :) I've fixed the spaces issue and will publish a new version after CI tests have passed

**Comment by aerhard** [comment]
see #38
