### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by reedstrm** [aerhard/linter-autocomplete-jing#49]
Don't think this is local to my setup - updated atom, and got this deprecation warning:

Argument to `path.dirname` must be a string
```
Object.dirname (/usr/share/atom/resources/app/src/electron-shims.js:9:10)
parseRule (/home/reedstrm/.atom/packages/linter-autocomplete-jing/lib/main.coffee:3230:23)
arrayMap (/home/reedstrm/.atom/packages/linter-autocomplete-jing/lib/main.coffee:1552:21)
map$1 (/home/reedstrm/.atom/packages/linter-autocomplete-jing/lib/main.coffee:1697:10)
<unknown> (/home/reedstrm/.atom/packages/linter-autocomplete-jing/lib/main.coffee:2314:12)
<unknown> (/home/reedstrm/.atom/packages/linter-autocomplete-jing/lib/main.coffee:2214:42)
```

**Comment by aerhard** [comment]
Thanks for reporting! I'll update the project in the next couple of days

**Comment by sean-fitzpatrick** [comment]
I am getting a nearly identical warning; attempting an initial setup.
Our system is running Atom 1.16.

It's entirely possible that I haven't managed to understand the configuration process.
I'm attempting to set up Atom for textbook authoring using [https://pretextbook.org](PreTeXt) using the RNG schema at [https://github.com/rbeezer/mathbook/tree/dev/schema](https://github.com/rbeezer/mathbook/tree/dev/schema).

What I've tried so far is to associate the .ptx file extension to text.xml, and then to add the following to config.cson:

```
"linter-autocomplete-jing":
    rules: [
      {
        priority: 1
        test:
          pathRegex: "\\.rng$"
        outcome:
          schemaProps: [
            {
              lang: "rng"
              path: "/home/fitzpat/github/mathbook/schema/pretext.rng"
            }
          ]
      }
    ]
```
But the above gets stripped when I try to save, and I get the deprecation warning.
Any advice you can give is appreciated.
