### ISSUE TITLE
Linter show wrong line number

### ISSUE THREAD

**Issue by pabian84** [aerhard/linter-autocomplete-jing#52]
![k-20180103-491295](https://user-images.githubusercontent.com/31716595/34509296-a37f7106-f08b-11e7-95f2-18da1a5bfaa5.png)

Wrong line is 4. But message is Line 1:1. How fix it?

**Comment by aerhard** [comment]
This is fixed in the current version. The error gets assigned to line 6 instead of line 4 though, since it's only certain at the parent element's  end tag `</elements>` that `<element>` in line 4 is neither self-closing nor has a corresponding end tag `</element>`.
