### ISSUE TITLE
localRootname rule in config.cson not working

### ISSUE THREAD

**Issue by holger-bauer** [aerhard/linter-autocomplete-jing#60]
I need to reference a certain xsd depending on the root element used in XML.
The root element used is  <grosskommentar>

To do this I've defined a rule in config.cson. However, when I load any matching XML file there's no validation or autocompletion done.
```coffeescript
  "linter-autocomplete-jing":
    rules: [
      {
      priority: 2
      test:
        rootLocalName: "grosskommentar"
      outcome:
        schemaProps: [
          {
            lang: "xsd"
            path: "/home/holger/Dokumente/specs/SF5-Schema 0.7.1/Schema/verlag-sf.xsd"
          }
        ]
    }
]
```

**Comment by aerhard** [comment]
The `linter-autocomplete-jing` settings don't take effect when declared on the top level of `config.cson`. In order to make Atom take them into account, you can add them as a property of the global settings key ("*") like this:

```
"*":
  "linter-autocomplete-jing":
    rules: []
```

I'll add this to the documentation on the next release.
