### ISSUE TITLE
errors reported on partial names

### ISSUE THREAD

**Issue by PietroLiuzzo** [aerhard/linter-autocomplete-jing#62]
A colleague using this package to validate XML for our project have for some time been experiencing stray characters appearing in edits using Atom. 

They are seeing the following error 

![image](https://user-images.githubusercontent.com/39619238/75367166-c5dbd780-58b7-11ea-903d-c06caf8dfba3.png)

which looks like the validation is happening on partial element names only or something similar

Do you have any idea what may be the issue?

thank you very much

**Comment by aerhard** [comment]
My apologies for the late reply. The error messages in the screenshot indicate that they refer to previous states of Atom's editor buffer. So the issue appears to be that these outdated messages didn't get cleared when the editor buffer changed to its current state. I can't reproduce the issue when all other Atom packages are up to date but I was able to encounter it when using an old version of the `linter-ui-default` Atom package (v1.7.0) in combination with a recent version of the `linter` package (in my case, v3.3.0). Updating `linter-ui-default` to the latest version should resolve this issue.

**Comment by PietroLiuzzo** [comment]
Thanks a lot! this solves the issue for us.
